-- DB 생성
CREATE DATABASE IF NOT EXISTS board
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

-- DB 사용
USE board;

-- 게시글 테이블 생성
CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);